### ISSUE TITLE
ability to express confidence in an annotation

### ISSUE THREAD

**Issue by balmas** [ld4lt/linguistic-annotation#1]
I don't see ability to express a level of confidence in an annotation listed in the requirements document at https://github.com/ld4lt/linguistic-annotation/blob/master/survey/required-features.md. NIF supports this. I don't think Web Annotation does explicitly but it could be done as an annotation on an annotation. I think it is a common need for linguistic annotations.

**Comment by chiarcos** [comment]
I would see that in connection with https://github.com/ld4lt/linguistic-annotation/blob/master/survey/required-features.md#b16-provenance. I add a clarifying remark that provenance explicitly includes information such as confidence level.
